export const product = [
    {
        id: 0,
        type:"Vegetables",
        imageId: "avacado_1",
        price: 100,
        name: "Avacado",
    },
    {
        id: 1,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Cabbage",
    },
    {
        id: 2,
        type:"Vegetables",
        imageId: "pea_1",
        price: 100,
        name: "Pea",
    },
    {
        id: 3,
        type:"Vegetables",
        imageId: "potato_1",
        price: 100,
        name: "Potato",
    },
    {
        id: 4,
        type:"Fruits",
        imageId: "watermalone_1",
        price: 100,
        name: "Watermelon",
    },
    {
        id: 5,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Oranges",
    },
    {
        id: 6,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Grapes",
    },
    {
        id: 7,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 8,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 9,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 10,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 11,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 12,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 13,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 14,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    },
    {
        id: 15,
        type:"Vegetables",
        imageId: "cabbage_1",
        price: 100,
        name: "Tomatoes",
    }

]